ALL:
	@python3 whatis.py 
	@python3 whatis.py "hello"
	@python3 whatis.py "20"
	@python3 whatis.py "20" "20"
	@python3 whatis.py "+--------20"
	@python3 whatis.py "+--------19"
	@python3 whatis.py "+--------19" "hee"
test:
	#python3 whatis.py "what" "thts"
	#python3 whatis.py "what" "thts" "what"


